version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11-browsers
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Verify Chromium and Chromedriver
          command: |
            echo "Проверяем установку Chromium и Chromedriver..."
            chromium-browser --version || echo "Chromium не установлен"
            chromedriver --version || echo "Chromedriver не установлен"
            ls -l /usr/bin/chromium-browser || echo "Chromium отсутствует"
            ls -l /usr/bin/chromedriver || echo "Chromedriver отсутствует"
      - run:
          name: Create Virtual Environment
          command: python -m venv venv
      - run:
          name: Install Python Dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - save_cache:
          key: v1-venv-cache-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - v1-venv-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Verify Chromium and Chromedriver before Tests
          command: |
            echo "Проверяем пути перед запуском тестов..."
            chromium-browser --version
            chromedriver --version
            ls -l /usr/bin/chromium-browser
            ls -l /usr/bin/chromedriver
      - run:
          name: Run API Tests
          command: |
            . venv/bin/activate
            echo "Using built-in Chromium and Chromedriver..."
            mkdir -p test_results
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
