version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.11
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install -y wget unzip nodejs npm
      - run:
          name: Install Puppeteer
          command: |
            npm install -g @puppeteer/browsers
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            npx @puppeteer/browsers install chrome@stable --path /root/project/chrome_installation
            cp /root/project/chrome_installation/chromedriver /usr/local/bin/
      - run:
          name: Create virtual environment if not exists
          command: |
            if [ ! -d "venv" ]; then
              python -m venv venv
            fi
      - run:
          name: Install Python dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - save_cache:
          key: v1-venv-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
      - run:
          name: Clean previous results
          command: |
            rm -rf test_results || true
            mkdir -p test_results
      - run:
          name: Activate virtual environment and run API Tests
          command: |
            . venv/bin/activate
            python -m pytest --alluredir=test_results/
      - run:
          name: Activate virtual environment and run UI Tests
          command: |
            . venv/bin/activate
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
