version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.11
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
            apt-get install -y nodejs
      - run:
          name: Install Puppeteer locally
          command: |
            npm install @puppeteer/browsers
      - run:
          name: Create virtual environment if not exists
          command: |
            if [ ! -d "venv" ]; then
              python -m venv venv
            fi
      - run:
          name: Install Python dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - save_cache:
          key: v1-venv-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
      - run:
          name: Use Puppeteer to install Chrome and ChromeDriver
          command: |
            npx @puppeteer/browsers install chrome@stable --path /root/project/chrome_installation
      - run:
          name: Clean previous results
          command: |
            rm -rf test_results || true
            mkdir -p test_results
      - run:
          name: Activate virtual environment and run tests
          command: |
            . venv/bin/activate
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
