version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/project

jobs:
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y wget curl unzip gnupg
            curl -sS https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - run:
          name: Setup Python Virtual Environment
          command: |
            python3 -m venv venv
            echo "source venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Python Dependencies
          command: |
            source venv/bin/activate
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - venv
