version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11.0
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            sudo apt-get update && sudo apt-get install -y nodejs npm
      - run:
          name: Verify npm and npx installation
          command: |
            npm --version
            npx --version
      - run:
          name: Create virtual environment if not exists
          command: |
            python -m venv venv
      - run:
          name: Install Python dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - save_cache:
          key: v1-venv-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
      - run:
          name: Clean previous results
          command: |
            rm -rf test_results || true
            mkdir -p test_results
      - run:
          name: Activate virtual environment and run tests
          command: |
            . venv/bin/activate
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
