version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11-browsers
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Create Virtual Environment
          command: python -m venv venv
      - run:
          name: Install Chromium
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium-browser
      - run:
          name: Install Chromedriver
          command: |
            sudo apt-get update
            sudo apt-get install -y chromium-chromedriver
      - run:
          name: Verify Chromium Installation
          command: |
            echo "Проверяем установку Chromium..."
            chromium-browser --version || echo "Chromium не установлен"
      - run:
          name: Install Python Dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - save_cache:
          key: v1-venv-cache-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - v1-venv-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Debug Environment Variables
          command: |
            echo "Debugging environment variables..."
            echo "PATH: $PATH"
            echo "CHROME_BINARY before setting: $CHROME_BINARY"
            echo "CHROMEDRIVER_PATH before setting: $CHROMEDRIVER_PATH"
      - run:
          name: Set Environment Variables
          command: |
            . venv/bin/activate
            export CHROME_BINARY=$(which chromium-browser)
            export CHROMEDRIVER_PATH=$(which chromedriver)
            echo "export CHROME_BINARY=$CHROME_BINARY" >> $BASH_ENV
            echo "export CHROMEDRIVER_PATH=$CHROMEDRIVER_PATH" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify Environment Variables
          command: |
            . venv/bin/activate
            source $BASH_ENV
            echo "CHROME_BINARY: $CHROME_BINARY"
            echo "CHROMEDRIVER_PATH: $CHROMEDRIVER_PATH"
            if [ -z "$CHROME_BINARY" ] || [ -z "$CHROMEDRIVER_PATH" ]; then
              echo "Переменные окружения не установлены"
              exit 1
            fi
      - run:
          name: Run API Tests
          command: |
            . venv/bin/activate
            source $BASH_ENV
            mkdir -p test_results
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
