version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11-browsers
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Chrome and Chromedriver
          command: |
            sudo apt-get update && sudo apt-get install -y wget curl gnupg unzip
            echo "Скачиваем Chrome и Chromedriver напрямую с предоставленных ссылок..."
            
            # Скачиваем Chrome
            wget -O chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.108/linux64/chrome-linux64.zip
            unzip chrome-linux64.zip -d /usr/local/bin/
            sudo chmod -R +x /usr/local/bin/chrome-linux64/
            rm chrome-linux64.zip
            echo "Chrome установлен."

            # Скачиваем Chromedriver
            wget -O chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.108/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip -d /usr/local/bin/
            sudo mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            rm -rf chromedriver-linux64.zip /usr/local/bin/chromedriver-linux64/
            echo "Chromedriver установлен."
      - run:
          name: Verify Chrome and Chromedriver
          command: |
            /usr/local/bin/chrome-linux64/chrome --version || echo "Chrome не установлен"
            /usr/local/bin/chromedriver --version || echo "Chromedriver не установлен"
      - run:
          name: Create Virtual Environment
          command: python -m venv venv
      - run:
          name: Install Python Dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - save_cache:
          key: v1-venv-cache-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - v1-venv-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Verify Chrome and Chromedriver before Tests
          command: |
            /usr/local/bin/chrome-linux64/chrome --version
            /usr/local/bin/chromedriver --version
      - run:
          name: Run API Tests
          command: |
            . venv/bin/activate
            mkdir -p test_results
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
