version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.11-slim
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            apt-get update && apt-get install -y wget curl unzip gnupg
            curl -sS https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
            apt-get update && apt-get install -y google-chrome-stable
      - run:
          name: Verify Google Chrome Installation
          command: |
            google-chrome --version
            which google-chrome || echo "Google Chrome не найден"
      - run:
          name: Add Chrome to PATH
          command: echo 'export PATH=$PATH:/usr/bin' >> $BASH_ENV
      - run:
          name: Create Virtual Environment
          command: python -m venv venv
      - run:
          name: Install Python Dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Create Virtual Environment
          command: python -m venv venv
      - run:
          name: Activate Virtual Environment and Install Dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run API Tests
          command: |
            . venv/bin/activate
            mkdir -p test_results
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
