version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11.0  # Обновленный образ Python
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
      - run:
          name: Create and activate virtual environment
          command: |
            python -m venv venv
            echo "source venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Python dependencies
          command: |
            source venv/bin/activate
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - save_cache:
          key: v1-venv-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
      - run:
          name: Activate virtual environment and clean previous results
          command: |
            source venv/bin/activate
            rm -rf test_results || true
            mkdir -p test_results
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
