version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.11
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            apt-get update
            apt-get install -y wget unzip nodejs npm
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
            apt-get update
            apt-get install -y google-chrome-stable
            wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip -d /usr/local/bin
            rm chromedriver_linux64.zip
      - run:
          name: Create virtual environment if not exists
          command: |
            if [ ! -d "venv" ]; then
              python -m venv venv
            fi
      - run:
          name: Install Python dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - save_cache:
          key: v1-venv-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
      - run:
          name: Clean previous results
          command: |
            rm -rf test_results || true
            mkdir -p test_results
      - run:
          name: Activate virtual environment and run API Tests
          command: |
            . venv/bin/activate
            python -m pytest --alluredir=test_results/
      - run:
          name: Activate virtual environment and run UI Tests
          command: |
            . venv/bin/activate
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
