version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11.0
    working_directory: ~/project

jobs:
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            python -m venv venv
            echo "source venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip setuptools wheel
            pip install -r requirements.txt
      - persist_to_workspace:
          root: .
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Activate Environment and Run Tests
          command: |
            source venv/bin/activate
            mkdir -p test_results
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - run-tests:
          requires:
            - setup
