version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.11-slim
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Create virtual environment
          command: python -m venv venv
      - run:
          name: Install Python dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install pytest
            pip install -r requirements.txt
      - save_cache:
          key: v1-venv-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-venv-{{ checksum "requirements.txt" }}
      - run:
          name: Create Results Directory
          command: mkdir -p results
      - run:
          name: Activate virtual environment and run API Tests
          command: |
            . venv/bin/activate
            Xvfb :99 -ac &
            export DISPLAY=:99
            sleep 10 # Allow Xvfb to initialize
            python -m pytest --alluredir=test_results/
      - run:
          name: Setup Selenium WebDriver
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip xvfb
            wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip -d /usr/local/bin
            rm chromedriver_linux64.zip
      - run:
          name: Activate virtual environment and run UI Tests
          command: |
            . venv/bin/activate
            Xvfb :99 -ac &
            export DISPLAY=:99
            sleep 10 # Allow Xvfb to initialize
            python -m pytest --alluredir=test_results/
      - store_test_results:
          path: results
      - store_artifacts:
          path: results

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
