version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11-browsers
    working_directory: ~/project

jobs:
  install-dependencies:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install Chrome and Chromedriver
          command: |
            sudo apt-get update && sudo apt-get install -y wget curl gnupg unzip libnss3 libxss1 libgconf-2-4 libasound2
            echo "Скачиваем Chrome и Chromedriver напрямую с предоставленных ссылок..."
            
            # Скачиваем Chrome
            wget -O chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.108/linux64/chrome-linux64.zip
            unzip chrome-linux64.zip -d /usr/local/bin/
            sudo chmod -R +x /usr/local/bin/chrome-linux64/
            rm chrome-linux64.zip
            echo "Chrome установлен."

            # Скачиваем Chromedriver
            wget -O chromedriver-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.108/linux64/chromedriver-linux64.zip
            unzip chromedriver-linux64.zip -d /usr/local/bin/
            sudo mv /usr/local/bin/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            rm -rf chromedriver-linux64.zip /usr/local/bin/chromedriver-linux64/
            echo "Chromedriver установлен."
      - run:
          name: Verify Chrome and Chromedriver Installation
          command: |
            echo "Проверяем содержимое /usr/local/bin:"
            ls -l /usr/local/bin/
            
            echo "Проверяем содержимое /usr/local/bin/chrome-linux64:"
            ls -l /usr/local/bin/chrome-linux64 || echo "Папка chrome-linux64 отсутствует"
            
            echo "Проверяем запуск Chrome:"
            /usr/local/bin/chrome-linux64/chrome --version || echo "Chrome не запускается"
            
            echo "Проверяем запуск Chromedriver:"
            /usr/local/bin/chromedriver --version || echo "Chromedriver не запускается"
      - run:
          name: Create Virtual Environment
          command: python -m venv venv
      - run:
          name: Install Python Dependencies
          command: |
            . venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - save_cache:
          key: v1-pip-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
      - save_cache:
          key: v1-venv-cache-{{ checksum "requirements.txt" }}
          paths:
            - venv

  run-tests:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pip-cache-{{ checksum "requirements.txt" }}
      - restore_cache:
          keys:
            - v1-venv-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Verify Chrome and Chromedriver before Tests
          command: |
            echo "Проверяем запуск Chrome перед тестами:"
            /usr/local/bin/chrome-linux64/chrome --version || echo "Chrome не найден"
            
            echo "Проверяем запуск Chromedriver перед тестами:"
            /usr/local/bin/chromedriver --version || echo "Chromedriver не найден"
      - run:
          name: Run API Tests
          command: |
            . venv/bin/activate
            mkdir -p test_results
            python -m pytest --alluredir=test_results/ --capture=tee-sys -v
      - store_test_results:
          path: test_results
      - store_artifacts:
          path: test_results
      - run:
          name: Debugging Logs
          command: |
            mkdir -p ~/debug_logs
            ls -l /usr/local/bin/ > ~/debug_logs/bin_contents.txt
            ls -l /usr/local/bin/chrome-linux64/ > ~/debug_logs/chrome_contents.txt || echo "chrome-linux64 отсутствует" >> ~/debug_logs/errors.txt
            /usr/local/bin/chrome-linux64/chrome --version > ~/debug_logs/chrome_version.txt || echo "Chrome не запускается" >> ~/debug_logs/errors.txt
            /usr/local/bin/chromedriver --version > ~/debug_logs/chromedriver_version.txt || echo "Chromedriver не запускается" >> ~/debug_logs/errors.txt
      - store_artifacts:
          path: ~/debug_logs

workflows:
  version: 2
  test-and-build:
    jobs:
      - install-dependencies
      - run-tests:
          requires:
            - install-dependencies
